coverage:
  range: "80...100"
  coverage:
    status:
      patch: false
      changes: false
      project:
        default:
          target: '80'

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no
