coverage:
  range: "80...100"
  coverage:
    status:
      patch: false
      changes: false
      project:
        default:
          target: '80'
  notify:
    after_n_builds: 24
    wait_for_ci: yes

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no
