codecov:
  require_ci_to_pass: yes
  wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

comment: false

ignore:
  - "src/virtualenv/create/via_global_ref/builtin/python2/site.py"
  - "src/virtualenv/create/via_global_ref/_virtualenv.py"
  - "src/virtualenv/activation/python/activate_this.py"
