"""Run pytest, tolerating GraalVM's polyglot interpreter-shutdown crash after a clean run."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree as ET  # ruff:ignore[suspicious-xml-etree-import] junit report is generated by our own pytest run, not untrusted


def main() -> None:
    junit_path = Path(sys.argv[1])
    result = subprocess.run([sys.executable, "-m", "pytest", *sys.argv[2:]], check=False)
    if result.returncode == 0 or not junit_path.exists() or not _junit_report_is_clean(junit_path):
        raise SystemExit(result.returncode)
    print(  # ruff:ignore[print]
        f"pytest exited {result.returncode} but the junit report shows no failed or errored tests; "
        "treating this as GraalVM's known interpreter-shutdown crash (see #3240) rather than failing the build.",
    )


def _junit_report_is_clean(junit_path: Path) -> bool:
    root = ET.parse(junit_path).getroot()  # ruff:ignore[suspicious-xml-element-tree-usage] same trusted, self-generated junit report
    suite = root if root.tag == "testsuite" else root.find("testsuite")
    return suite is not None and suite.get("failures") == "0" and suite.get("errors") == "0"


if __name__ == "__main__":
    main()
