"""Run pytest, tolerating GraalVM's polyglot interpreter-shutdown crash after a clean run."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Final
from xml.etree import ElementTree as ET  # ruff:ignore[suspicious-xml-etree-import] junit report is generated by our own pytest run, not untrusted


def main() -> None:
    junit_path: Final[Path] = Path(sys.argv[1])
    junit_path.unlink(missing_ok=True)
    result: Final[subprocess.CompletedProcess[str]] = subprocess.run(
        [sys.executable, "-m", "pytest", *sys.argv[2:]],
        check=False,
        stderr=subprocess.PIPE,
        encoding="utf-8",
        errors="replace",
    )
    sys.stderr.write(result.stderr)
    if (
        result.returncode != 1
        or "did not complete all polyglot threads" not in result.stderr
        or not _junit_report_is_clean(junit_path)
    ):
        raise SystemExit(result.returncode)
    print(  # ruff:ignore[print]
        "GraalVM reported its known polyglot shutdown error after a completed test run (see #3240).",
    )


def _junit_report_is_clean(junit_path: Path) -> bool:
    try:
        root: Final[ET.Element] = ET.parse(junit_path).getroot()  # ruff:ignore[suspicious-xml-element-tree-usage] trusted pytest output
        suites: Final[list[ET.Element]] = list(root.iter("testsuite"))
        return (
            bool(suites)
            and all(suite.get("failures") == "0" and suite.get("errors") == "0" for suite in suites)
            and sum(int(suite.attrib["tests"]) - int(suite.get("skipped", "0")) for suite in suites) > 0
        )
    except (OSError, ET.ParseError, KeyError, ValueError):
        return False


__all__ = ["main"]


if __name__ == "__main__":
    main()
