"""Run pytest in parallel shards, tolerating GraalVM's polyglot interpreter-shutdown crash after a clean run."""

from __future__ import annotations

import os
import subprocess
import sys
import threading
from argparse import REMAINDER, ArgumentParser
from pathlib import Path
from typing import IO, TYPE_CHECKING, Final
from xml.etree import ElementTree as ET  # ruff:ignore[suspicious-xml-etree-import] junit report is generated by our own pytest run, not untrusted

if TYPE_CHECKING:
    from collections.abc import Sequence

_SHUTDOWN: Final[str] = "did not complete all polyglot threads"
_NO_TESTS_COLLECTED: Final[int] = 5


def main() -> None:
    parser: Final[ArgumentParser] = ArgumentParser(description=__doc__)
    parser.add_argument(
        "--shards",
        type=int,
        default=os.cpu_count() or 1,
        help="parallel pytest processes; xdist cannot run under GraalPy (see #3240)",
    )
    parser.add_argument("junit", type=Path, help="report path; shard K writes it with a .K.xml suffix")
    parser.add_argument("--group", default="1/1", help="K/N runner group; groups run disjoint shards")
    parser.add_argument("pytest_args", nargs=REMAINDER, help="arguments passed to every pytest process")
    args: Final = parser.parse_args()
    group, _, groups = args.group.partition("/")
    if not (group.isdecimal() and groups.isdecimal() and 1 <= int(group) <= int(groups)):
        parser.error("--group requires K/N with 1 <= K <= N")
    total: Final[int] = args.shards * int(groups)
    shards: Final[list[_Shard]] = [
        _Shard(index, total, args.junit, args.pytest_args) for index in range(int(group), total + 1, int(groups))
    ]
    executed: Final[list[int | None]] = [shard.wait() for shard in shards]
    if failed := [shard.label for shard, count in zip(shards, executed) if count is None]:
        msg = f"pytest shards failed: {', '.join(failed)}"
        raise SystemExit(msg)
    if not sum(filter(None, executed)):
        msg = "pytest shards ran no tests"
        raise SystemExit(msg)


class _Shard:
    def __init__(self, index: int, count: int, junit: Path, pytest_args: Sequence[str]) -> None:
        self.label: Final[str] = f"{index}/{count}"
        self.junit: Final[Path] = junit.with_suffix(f".{index}.xml")
        self.junit.unlink(missing_ok=True)
        self.stderr: Final[list[str]] = []
        # -u streams output as it happens; the shards run for many minutes
        self.process: Final[subprocess.Popen[str]] = subprocess.Popen(
            [
                sys.executable,
                "-u",
                "-m",
                "pytest",
                *pytest_args,
                f"--shard={self.label}",
                "--junitxml",
                str(self.junit),
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            encoding="utf-8",
            errors="replace",
        )
        self.pumps: Final[list[threading.Thread]] = [
            threading.Thread(target=self._pump, args=(self.process.stdout, sys.stdout, None)),
            threading.Thread(target=self._pump, args=(self.process.stderr, sys.stderr, self.stderr)),
        ]
        for pump in self.pumps:
            pump.start()

    def _pump(self, source: IO[str], sink: IO[str], lines: list[str] | None) -> None:
        for line in source:
            if lines is not None:
                lines.append(line)
            sink.write(f"[{self.label}] {line}")

    def wait(self) -> int | None:
        """Return how many tests ran, or None when the shard failed."""
        for pump in self.pumps:
            pump.join()
        status: Final[int] = self.process.wait()
        shutdown: Final[bool] = status == 1 and any(_SHUTDOWN in line for line in self.stderr)
        if status not in {0, _NO_TESTS_COLLECTED} and not shutdown:
            print(f"[{self.label}] exit {status}")  # ruff:ignore[print]
            return None
        if (executed := _executed_tests(self.junit)) is None:
            print(f"[{self.label}] exit {status} without a clean junit report")  # ruff:ignore[print]
            return None
        if shutdown:
            print(  # ruff:ignore[print]
                f"[{self.label}] GraalVM reported its known polyglot shutdown error after a completed test run"
                " (see #3240).",
            )
        return executed


def _executed_tests(junit_path: Path) -> int | None:
    try:
        root: Final[ET.Element] = ET.parse(junit_path).getroot()  # ruff:ignore[suspicious-xml-element-tree-usage] trusted pytest output
        suites: Final[list[ET.Element]] = list(root.iter("testsuite"))
        if not suites or any(suite.get("failures") != "0" or suite.get("errors") != "0" for suite in suites):
            return None
        return sum(int(suite.attrib["tests"]) - int(suite.get("skipped", "0")) for suite in suites)
    except (OSError, ET.ParseError, KeyError, ValueError):
        return None


__all__ = ["main"]


if __name__ == "__main__":
    main()
