name: 🧪 check
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 test ${{ matrix.py }} - ${{ matrix.os }}
    if: github.event_name != 'schedule' || github.repository_owner == 'pypa'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.13t"
#          - "3.13"
#          - "3.12"
#          - "3.11"
#          - "3.10"
#          - "3.9"
#          - "3.8"
#          - pypy-3.10
#          - pypy-3.9
#          - pypy-3.8
          - graalpy-24.1
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - { os: macos-latest, py: "brew@3.11" }
          - { os: macos-latest, py: "brew@3.10" }
          - { os: macos-latest, py: "brew@3.9" }
        exclude:
          - { os: windows-latest, py: "graalpy-24.1" }
          - { os: windows-latest, py: "pypy-3.10" }
          - { os: windows-latest, py: "pypy-3.9" }
          - { os: windows-latest, py: "pypy-3.8" }
    steps:
      - uses: taiki-e/install-action@cargo-binstall
#      - name: 🛠️ Install OS dependencies
#        run: |
#          for i in 1 2 3; do
#            echo "try $i" && \
#            if [ "${{ runner.os }}" = "Linux" ]; then
#              sudo apt-get install -y software-properties-common
#              sudo apt-add-repository ppa:fish-shell/release-4 -y
#              sudo apt-get update -y
#              sudo apt-get install snapd fish csh -y
#              cargo binstall -y nu
#            elif [ "${{ runner.os }}" = "macOS" ]; then
#              brew install fish tcsh nushell || brew upgrade fish tcsh nushell
#            elif [ "${{ runner.os }}" = "Windows" ]; then
#              choco install nushell
#            fi && exit 0 || true
#            sleep 1
#          done
#        shell: bash
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 🚀 Install the latest version of uv
        uses: astral-sh/setup-uv@v4
      - name: 📦 Install tox
        shell: bash
        run: |
          PYVER=$([[ "${{ matrix.py }}" == "3.13" || "${{ matrix.py }}" == "3.13t" ]] && echo 3.12 || echo 3.13)
          uv tool install --python-preference only-managed --python $PYVER tox --with tox-uv
      - name: 🐍 Setup Python for test ${{ matrix.py }}
        if: ${{ !startsWith(matrix.py, 'graalpy-') }}
        shell: bash
        run: |
          if [[ "${{ matrix.py }}" == brew@* ]]; then
            PY=$(echo '${{ matrix.py }}' | cut -c 6-)
            brew install python@$PY || brew upgrade python@$PY
            echo "/usr/local/opt/python@$PY/libexec/bin" >>"${GITHUB_PATH}"
          else
            uv python install -v --preview "${{ matrix.py }}"
          fi
      - name: 🐍 Setup Graal Python for test ${{ matrix.py }}
        if: ${{ startsWith(matrix.py, 'graalpy-') }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: 🧬 Pick environment to run
        shell: bash
        run: python tasks/pick_tox_env.py ${{ matrix.py }}
      - name: 📋 Print PATH entries
        shell: bash
        run: |
          echo "$PATH" | tr ':' '\n'
      - name: 🏗️ Setup test suite
        run: tox run -vvvv --notest --skip-missing-interpreters false
      - name: 🏃 Run test suite
        run: tox run --skip-pkg-install
        timeout-minutes: 20
        env:
          PYTEST_ADDOPTS: "-vv --durations=20"
          CI_RUN: "yes"
          DIFF_AGAINST: HEAD

#  check:
#    name: 🔎 check ${{ matrix.tox_env }} - ${{ matrix.os }}
#    if: github.event_name != 'schedule' || github.repository_owner == 'pypa'
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os:
#          - ubuntu-latest
#          - windows-latest
#        tox_env:
#          - dev
#          - docs
#          - readme
#          - upgrade
#          - zipapp
#        exclude:
#          - { os: windows-latest, tox_env: readme }
#          - { os: windows-latest, tox_env: docs }
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: 🚀 Install the latest version of uv
#        uses: astral-sh/setup-uv@v4
#      - name: 📦 Install tox
#        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv
#      - name: 🏗️ Setup check suite
#        run: tox run -vv --notest --skip-missing-interpreters false -e ${{ matrix.tox_env }}
#      - name: 🏃 Run check for ${{ matrix.tox_env }}
#        run: tox run --skip-pkg-install -e ${{ matrix.tox_env }}
